# ###################### #
#
# Crafting+ Reloaded v1.0
# Craft the Uncraftable
#
# ###################### #

# ------------------------------ #
# Message settings
# ------------------------------ #

#Message to a player if they do not have permission for a Crafting+ command.
permission-message: '&cCPR Error! You do not have permission to use this command!'

#Message to a player if the Crafting+ configuration was successfully reloaded.
reload-success-message: '&aThe CPR config has been successfully reloaded.'

#Message to player if they enter an invalid Crafting+ command.
invalid-command-message: '&cThat is an invalid command. Type ''/cpr help''
  for help.'

# ------------------------------ #
# Enable or Disable item recipes.
# ------------------------------ #

#Write true/false depending if you want that item recipe to be enabled/disabled.
#See Recipe List here: https://github.com/Chewsterchew/CraftingPlus/blob/master/recipes.md
enabled:
  disc13: true
  discCat: true
  discBlocks: true
  discChirp: true
  discFar: true
  discMall: true
  discMellohi: true
  discStal: true
  discStrad: true
  discWard: true
  disc11: true
  discWait: true
  ironHorseArmor: true
  goldHorseArmor: true
  diamondHorseArmor: true
  ice: true
  packedIce: true
  saddle: true
  nameTag: true
  cobWeb: true
  mobSpawner: false
