name: CraftingPlusReloaded
version: 1.0
description: This plugins adds crafting recipes for uncraftable vanilla items.
author: Chewsterchew
website: http://www.github.com/Chewsterchew

main: me.harrysmc.craftingplus.CraftingPlus

commands:
   cpr:
      description: Command to use craftingplus.
      aliases: [crafting+]

permissions:
    cpr.reload:
        description: Gives access to reload CPR config.
        default: op
